settings_form:
  path: 'settings_form'
  defaults:
    _controller: '\Drupal\settings_form\Controller\FormController::content'
    _title: 'Module configuration screen'
  requirements:
    _permission: 'access content'
